#!/usr/bin/python

palettes = {
        'light': [
            ('body', 'black', 'light gray'),
            ('header', 'white', 'dark blue'),
            ('footer', 'dark green', 'light gray'),
            ('importer', 'white', 'light blue'),
            ('exporter', 'light blue', 'dark gray'),
            ('diradder', 'dark blue', 'white'),
            ('search_box', 'dark blue', 'white'),
            ('search_box_active', 'black', 'yellow'),
            ('file', 'dark blue', 'light gray'),
            ('file focus', 'dark magenta', 'white'),
            ('dir', 'black', 'light gray'),
            ('dir focus','light red', 'white'),
            ('file select', 'white', 'light blue'),
            ('file select focus', 'light blue', 'dark gray'),
            ('dir select', 'white', 'light green'),
            ('dir select focus', 'light green', 'dark gray'),
            ('details', 'yellow', 'dark blue'),
            ('error', 'light red', 'light gray'),
            ('success', 'light green', 'white'),
            ('button', 'dark blue', 'light gray'),
            ('button focus', 'light blue', 'white'),
            ('sync', 'dark green,bold', 'light gray'),
            ('unsync', 'dark blue', 'light gray'),
            ('nosync', 'dark gray', 'light gray'),
            ('shared', 'white', 'dark gray'),
            ('loading', 'black,blink', 'light gray')
        ],
        'dark':[
            ('body', 'light gray', 'black'),
            ('header', 'white', 'dark magenta'),
            ('footer', 'light green', 'black'),
            ('importer', 'white', 'dark blue'),
            ('exporter', 'white', 'dark blue'),
            ('diradder', 'white', 'dark blue'),
            ('search_box', 'white', 'dark blue'),
            ('search_box_active', 'yellow', 'black'),
            ('file', 'light blue', 'black'),
            ('file focus', 'white', 'dark magenta'),
            ('dir', 'light gray', 'black'),
            ('dir focus', 'white','dark gray'),
            ('file select', 'white', 'light blue'),
            ('file select focus', 'dark gray', 'light blue'),
            ('dir select', 'white', 'light green'),
            ('dir select focus', 'dark gray', 'light green'),
            ('details', 'yellow', 'dark blue'),
            ('error', 'light red', 'black'),
            ('success', 'black', 'light green'),
            ('button', 'light gray', 'dark blue'),
            ('button focus', 'dark magenta', 'white'),
            ('sync', 'dark green,bold', 'black'),
            ('unsync', 'dark blue', 'black'),
            ('nosync', 'dark gray', 'black'),
            ('shared', 'white', 'dark gray'),
            ('loading', 'light gray,blink', 'black')
        ],
        'system defaults':[
            ('body', 'default', 'default'),
            ('header', 'default', 'default'),
            ('footer', 'default', 'default'),
            ('importer', 'default', 'default'),
            ('exporter', 'default', 'default'),
            ('diradder', 'default', 'default'),
            ('search_box', 'default', 'default'),
            ('search_box_active', 'default', 'default'),
            ('file', 'default', 'default'),
            ('file focus', 'default, standout', 'default'),
            ('dir', 'default', 'default'),
            ('dir focus','default,bold', 'default'),
            ('file select', 'default,underline', 'default'),
            ('file select focus', 'default,standout,underline', 'default'),
            ('dir select', 'default,underline', 'default'),
            ('dir select focus', 'default,bold,underline', 'default'),
            ('details', 'default', 'default'),
            ('error', 'default', 'default'),
            ('success', 'default,bold', 'default'),
            ('button', 'default', 'default'),
            ('button focus', 'default', 'default'),
            ('sync', 'default', 'default'),
            ('unsync', 'default', 'default'),
            ('nosync', 'default', 'default'),
            ('shared', 'default', 'default'),
            ('loading', 'default,blink', 'default')
        ]
    }
